// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnalyticsDaily struct {
	AnalyticsDate pgtype.Date
	TotalViews    int32
	TotalLikes    int32
	TotalDislikes int32
	TotalComments int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Category struct {
	CategoryID   pgtype.UUID
	CategoryName string
}

type Comment struct {
	CommentID    pgtype.UUID
	ContentID    pgtype.UUID
	UserID       pgtype.UUID
	CommentText  string
	LikeCount    int32
	DislikeCount int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	IsDeleted    pgtype.Bool
}

type CommentReaction struct {
	CommentID pgtype.UUID
	UserID    pgtype.UUID
	Reaction  string
}

type Content struct {
	ContentID           pgtype.UUID
	UserID              pgtype.UUID
	CategoryID          pgtype.UUID
	Title               string
	ContentDescription  string
	CommentsEnabled     bool
	ViewCountEnabled    bool
	LikeCountEnabled    bool
	DislikeCountEnabled bool
	Status              string
	ViewCount           int32
	LikeCount           int32
	DislikeCount        int32
	CommentCount        int32
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	PublishedAt         pgtype.Timestamptz
	IsDeleted           pgtype.Bool
}

type ContentReaction struct {
	ContentID pgtype.UUID
	UserID    pgtype.UUID
	Reaction  string
}

type ContentTag struct {
	ContentID pgtype.UUID
	TagID     pgtype.UUID
}

type GlobalSetting struct {
	GlobalSettingsID pgtype.UUID
	DisableComments  bool
	DisableLikes     bool
	DisableDislikes  bool
	DisableViews     bool
}

type Medium struct {
	MediaID      pgtype.UUID
	ContentID    pgtype.UUID
	MediaType    string
	MediaUrl     string
	MediaCaption string
	MediaOrder   int32
}

type Tag struct {
	TagID   pgtype.UUID
	TagName string
}

type User struct {
	UserID    pgtype.UUID
	Username  string
	Email     string
	Password  string
	Pfp       string
	Role      string
	Banned    pgtype.Bool
	IsDeleted pgtype.Bool
	CreatedAt pgtype.Timestamptz
}
